In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dff = pd.read_csv("/content/Retail_Dataset_Cleaned (2).csv")
dff

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [3]:
dff.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [4]:
dff.isnull().sum()

Store_ID                 0
Store_Name               0
Brand_Name               0
Store_Type               0
City                     0
City_Tier                0
Product_Name             0
Category                 0
Sub_Category             0
Product_Stage            0
Quantity_Available       0
Units_Sold               0
Unit_Price               0
Cost_Price               0
Revenue                  0
Profit_Margin            0
Average_Order_Value      0
Inventory_Turnover       0
Days_of_Stock            0
Customer_Segment         0
Sales_Channel            0
Payment_Method           0
Supplier                 0
Supplier_Rating          0
Promotion_Type           0
Promotion_Impact         0
Max_Discount_Offered     0
Return_Rate              0
Return_Reason            0
Customer_Satisfaction    0
Online_Rating            0
Review_Count             0
Sales_Rep_Experience     0
Sales_Rep_Rating         0
Market_Share             0
Competition_Level        0
Competitor_Count         0
Brand_Loyalty            0
Brand_Awareness          0
Price_Competitiveness    0
Weather_Impact           0
Delivery_Time            0
Shipping_Cost            0
Month                    0
Year                     0
Quarter                  0
Season                   0
dtype: int64

In [5]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.8+ MB

In [6]:
fg = pd.pivot_table(dff,values = "Profit_Margin" , index= "Season" , aggfunc= "sum" )
fg

         Profit_Margin
Season
Monsoon       38290.71
Spring        18780.81
Summer        28777.85
Winter        29669.64

In [11]:
fg2 = pd.pivot_table(dff, values="Profit_Margin", index="Season", aggfunc="median")
fg2

         Profit_Margin
Season
Monsoon          22.46
Spring           22.55
Summer           22.45
Winter           22.31

In [12]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(15), int64(10), object(22)
memory usage: 1.8+ MB

In [13]:
rt = pd.pivot_table(dff,values = "Shipping_Cost" , index = ["Season","Weather_Impact"] ,
                    aggfunc= "sum")
rt

                        Shipping_Cost
Season  Weather_Impact
Monsoon High                  29061.0
        Low                  220102.0
        Medium                30144.0
Spring  Low                  118902.0
        Medium                21664.0
Summer  High                  56152.0
        Low                  136429.0
        Medium                11153.0
Winter  Low                  184455.0
        Medium                34377.0

In [15]:
rt3 = pd.pivot_table(dff,values = "Shipping_Cost" , index = ["Season","Weather_Impact"] ,
                    aggfunc= ["sum" , "mean"])
rt3

                                 sum          mean
                       Shipping_Cost Shipping_Cost
Season  Weather_Impact
Monsoon High                 29061.0    199.047945
        Low                 220102.0    174.822875
        Medium               30144.0     98.832787
Spring  Low                 118902.0    190.243200
        Medium               21664.0    101.708920
Summer  High                 56152.0    192.962199
        Low                 136429.0    156.995397
        Medium               11153.0     99.580357
Winter  Low                 184455.0    187.074037
        Medium               34377.0    101.108824

In [17]:
rt5 = pd.pivot_table(dff,values = ["Shipping_Cost","Market_Share"] , index = ["Season","Weather_Impact"] ,
                    aggfunc= {"Shipping_Cost" : "median" ,"Market_Share" : "sum" })
rt5

                        Market_Share  Shipping_Cost
Season  Weather_Impact
Monsoon High                  1942.4          118.5
        Low                  20121.6          130.0
        Medium                4153.8          102.0
Spring  Low                  10052.4          136.0
        Medium                2869.7          102.0
Summer  High                  3984.1          112.0
        Low                  14300.5          126.0
        Medium                1506.8          100.5
Winter  Low                  15772.6          135.0
        Medium                4564.9          100.0

In [19]:
dff.groupby("Season")["Market_Share"].sum()

Season
Monsoon    26217.8
Spring     12922.1
Summer     19791.4
Winter     20337.5
Name: Market_Share, dtype: float64

In [20]:
dff.groupby(["Season","Weather_Impact"])["Market_Share"].sum()

Season   Weather_Impact
Monsoon  High               1942.4
         Low               20121.6
         Medium             4153.8
Spring   Low               10052.4
         Medium             2869.7
Summer   High               3984.1
         Low               14300.5
         Medium             1506.8
Winter   Low               15772.6
         Medium             4564.9
Name: Market_Share, dtype: float64

In [22]:
dff.groupby(["Season","Weather_Impact"])[["Market_Share" , "Online_Rating"]].sum()

                        Market_Share  Online_Rating
Season  Weather_Impact
Monsoon High                  1942.4          645.4
        Low                  20121.6         5531.5
        Medium                4153.8         1343.2
Spring  Low                  10052.4         2741.4
        Medium                2869.7          942.1
Summer  High                  3984.1         1290.9
        Low                  14300.5         3819.6
        Medium                1506.8          493.6
Winter  Low                  15772.6         4315.2
        Medium                4564.9         1492.3

In [23]:
import random

In [28]:
t = np.random.randint(1, 6, size=len(dff))
print("shape:" , dff.shape)
print("len" , len(t))

shape: (5146, 47)
len 5146

In [29]:
dff.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [30]:
dff.insert(2 ,"ratt" , t)

In [31]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   ratt                   5146 non-null   int64
 3   Brand_Name             5146 non-null   object
 4   Store_Type             5146 non-null   object
 5   City                   5146 non-null   object
 6   City_Tier              5146 non-null   object
 7   Product_Name           5146 non-null   object
 8   Category               5146 non-null   object
 9   Sub_Category           5146 non-null   object
 10  Product_Stage          5146 non-null   object
 11  Quantity_Available     5146 non-null   float64
 12  Units_Sold             5146 non-null   float64
 13  Unit_Price             5146 non-null   int64
 14  Cost_Price             5146 non-null   int64
 15  Revenue                5146 non-null   float64
 16  Profit_Margin          5146 non-null   float64
 17  Average_Order_Value    5146 non-null   int64
 18  Inventory_Turnover     5146 non-null   float64
 19  Days_of_Stock          5146 non-null   int64
 20  Customer_Segment       5146 non-null   object
 21  Sales_Channel          5146 non-null   object
 22  Payment_Method         5146 non-null   object
 23  Supplier               5146 non-null   object
 24  Supplier_Rating        5146 non-null   object
 25  Promotion_Type         5146 non-null   object
 26  Promotion_Impact       5146 non-null   float64
 27  Max_Discount_Offered   5146 non-null   int64
 28  Return_Rate            5146 non-null   float64
 29  Return_Reason          5146 non-null   object
 30  Customer_Satisfaction  5146 non-null   float64
 31  Online_Rating          5146 non-null   float64
 32  Review_Count           5146 non-null   int64
 33  Sales_Rep_Experience   5146 non-null   int64
 34  Sales_Rep_Rating       5146 non-null   float64
 35  Market_Share           5146 non-null   float64
 36  Competition_Level      5146 non-null   object
 37  Competitor_Count       5146 non-null   int64
 38  Brand_Loyalty          5146 non-null   float64
 39  Brand_Awareness        5146 non-null   float64
 40  Price_Competitiveness  5146 non-null   object
 41  Weather_Impact         5146 non-null   object
 42  Delivery_Time          5146 non-null   float64
 43  Shipping_Cost          5146 non-null   float64
 44  Month                  5146 non-null   int64
 45  Year                   5146 non-null   int64
 46  Quarter                5146 non-null   object
 47  Season                 5146 non-null   object
dtypes: float64(15), int64(11), object(22)
memory usage: 1.9+ MB

In [33]:
d4 = dff[["Store_Name","ratt","Season"]].head(3)
d5 = dff[["Store_Name","ratt","Season"]].tail(3)

In [35]:
d4

                       Store_Name  ratt  Season
0    Brandx_India Superstore Pune     2  Spring
1  Brandx_India Superstore Mumbai     4  Spring
2        Brandx_India Trends Pune     2  Spring

In [36]:
d5

                           Store_Name  ratt   Season
5143  Brandx_India Gadget Zone Kanpur     5  Monsoon
5144        Brandx_India Style Mumbai     5   Winter
5145   Brandx_India Electronics Delhi     3  Monsoon

In [43]:
we = d4.join(d5 , lsuffix= "core" , on= "ratt" , )
we

                   Store_Namecore  rattcore Seasoncore Store_Name  ratt Season
0    Brandx_India Superstore Pune         2     Spring        NaN   NaN    NaN
1  Brandx_India Superstore Mumbai         4     Spring        NaN   NaN    NaN
2        Brandx_India Trends Pune         2     Spring        NaN   NaN    NaN

In [39]:
we

                   Store_Namecore  rattcore Seasoncore Store_Name  ratt Season
0    Brandx_India Superstore Pune         2     Spring        NaN   NaN    NaN
1  Brandx_India Superstore Mumbai         4     Spring        NaN   NaN    NaN
2        Brandx_India Trends Pune         2     Spring        NaN   NaN    NaN

In [46]:
d4

                       Store_Name  ratt  Season
0    Brandx_India Superstore Pune     2  Spring
1  Brandx_India Superstore Mumbai     4  Spring
2        Brandx_India Trends Pune     2  Spring

In [47]:
d5

                           Store_Name  ratt   Season
5143  Brandx_India Gadget Zone Kanpur     5  Monsoon
5144        Brandx_India Style Mumbai     5   Winter
5145   Brandx_India Electronics Delhi     3  Monsoon

In [49]:
pd.merge(d5,d4 ,on = "ratt" ,how = "left")

                      Store_Name_x  ratt Season_x Store_Name_y Season_y
0  Brandx_India Gadget Zone Kanpur     5  Monsoon          NaN      NaN
1        Brandx_India Style Mumbai     5   Winter          NaN      NaN
2   Brandx_India Electronics Delhi     3  Monsoon          NaN      NaN

In [53]:
pd.merge(d5, d4, on="ratt")

Empty DataFrame
Columns: [Store_Name_x, ratt, Season_x, Store_Name_y, Season_y]
Index: []

In [54]:
d4

                       Store_Name  ratt  Season
0    Brandx_India Superstore Pune     2  Spring
1  Brandx_India Superstore Mumbai     4  Spring
2        Brandx_India Trends Pune     2  Spring

In [55]:
d5

                           Store_Name  ratt   Season
5143  Brandx_India Gadget Zone Kanpur     5  Monsoon
5144        Brandx_India Style Mumbai     5   Winter
5145   Brandx_India Electronics Delhi     3  Monsoon

In [56]:
pd.concat([d4,d5])

                           Store_Name  ratt   Season
0        Brandx_India Superstore Pune     2   Spring
1      Brandx_India Superstore Mumbai     4   Spring
2            Brandx_India Trends Pune     2   Spring
5143  Brandx_India Gadget Zone Kanpur     5  Monsoon
5144        Brandx_India Style Mumbai     5   Winter
5145   Brandx_India Electronics Delhi     3  Monsoon

In [57]:
pd.concat([d4,d5] , axis = 1)

,Store_Name,ratt,Season,Store_Name,ratt,Season
0,Brandx_India Superstore Pune,2.0,Spring,NaN,NaN,NaN
1,Brandx_India Superstore Mumbai,4.0,Spring,NaN,NaN,NaN
2,Brandx_India Trends Pune,2.0,Spring,NaN,NaN,NaN
5143,NaN,NaN,NaN,Brandx_India Gadget Zone Kanpur,5.0,Monsoon
5144,NaN,NaN,NaN,Brandx_India Style Mumbai,5.0,Winter
5145,NaN,NaN,NaN,Brandx_India Electronics Delhi,3.0,Monsoon

In [58]:
d4

                       Store_Name  ratt  Season
0    Brandx_India Superstore Pune     2  Spring
1  Brandx_India Superstore Mumbai     4  Spring
2        Brandx_India Trends Pune     2  Spring

In [60]:
d4["ratt"].unique()

array([2, 4])

In [61]:
d4["ratt"].nunique()

2

In [62]:
idd = [1212 , 1515 , np.nan , 7878]
name = ["X","Y","Z",np.nan]
age = [np.nan , 2,7,np.nan]

In [63]:
drr = pd.DataFrame({"IDD" : idd , "NAME" : name , "AGE" :age})
drr

      IDD NAME  AGE
0  1212.0    X  NaN
1  1515.0    Y  2.0
2     NaN    Z  7.0
3  7878.0  NaN  NaN

In [64]:
drr.isnull().sum()

IDD     1
NAME    1
AGE     2
dtype: int64

In [65]:
drr.fillna(7777)

      IDD  NAME     AGE
0  1212.0     X  7777.0
1  1515.0     Y     2.0
2  7777.0     Z     7.0
3  7878.0  7777  7777.0

In [67]:
drr

      IDD NAME  AGE
0  1212.0    X  NaN
1  1515.0    Y  2.0
2     NaN    Z  7.0
3  7878.0  NaN  NaN

In [66]:
drr.fillna(method = "ffill")

/tmp/ipykernel_1295/1700211187.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drr.fillna(method = "ffill")

      IDD NAME  AGE
0  1212.0    X  NaN
1  1515.0    Y  2.0
2  1515.0    Z  7.0
3  7878.0    Z  7.0

In [68]:
drr

      IDD NAME  AGE
0  1212.0    X  NaN
1  1515.0    Y  2.0
2     NaN    Z  7.0
3  7878.0  NaN  NaN

In [69]:
drr.fillna(method = "bfill")

/tmp/ipykernel_1295/563887554.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drr.fillna(method = "bfill")

      IDD NAME  AGE
0  1212.0    X  2.0
1  1515.0    Y  2.0
2  7878.0    Z  7.0
3  7878.0  NaN  NaN

In [70]:
drr.fillna(method = "ffill" , axis = 1)

/tmp/ipykernel_1295/3358507726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drr.fillna(method = "ffill" , axis = 1)
/tmp/ipykernel_1295/3358507726.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  drr.fillna(method = "ffill" , axis = 1)

      IDD    NAME     AGE
0  1212.0       X       X
1  1515.0       Y     2.0
2     NaN       Z     7.0
3  7878.0  7878.0  7878.0

In [71]:
drr.fillna(method = "bfill" , axis = 1)

/tmp/ipykernel_1295/3808997437.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drr.fillna(method = "bfill" , axis = 1)
/tmp/ipykernel_1295/3808997437.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  drr.fillna(method = "bfill" , axis = 1)

      IDD NAME  AGE
0  1212.0    X  NaN
1  1515.0    Y  2.0
2       Z    Z  7.0
3  7878.0  NaN  NaN