In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [4]:
data = pd.read_csv("/content/Retail_Dataset_Cleaned (3).csv")
data

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [12]:
data.loc[[20,21,22] , ["Store_Type","Customer_Satisfaction"]]

    Store_Type  Customer_Satisfaction
20  Online Hub                    4.6
21    Flagship                    4.3
22  Online Hub                    4.4

In [5]:
from scipy import stats

In [6]:
flagship = data[data["Store_Type"]=="Flagship"]["Customer_Satisfaction"]

mall = data[data["Store_Type"]=="Mall Store"]["Customer_Satisfaction"]

In [10]:
data[data["Store_Type"]=="Flagship"]["Customer_Satisfaction"]

0       4.0
2       4.3
21      4.3
23      4.6
24      3.8
       ...
5124    3.9
5135    3.9
5136    4.5
5143    3.9
5145    4.7
Name: Customer_Satisfaction, Length: 1052, dtype: float64

In [7]:
flagship

0       4.0
2       4.3
21      4.3
23      4.6
24      3.8
       ...
5124    3.9
5135    3.9
5136    4.5
5143    3.9
5145    4.7
Name: Customer_Satisfaction, Length: 1052, dtype: float64

In [13]:
t_stat, p_value = stats.ttest_ind(flagship,mall,nan_policy="omit")

print("T Statistic:", t_stat)
print("P Value:", p_value)

T Statistic: 0.5195690551232559
P Value: 0.6034184941873542

In [14]:
if p_value < 0.05:
    print("Reject Null Hypothesis")
else:
    print("Fail to Reject Null Hypothesis")

Fail to Reject Null Hypothesis

In [16]:
data.groupby("Customer_Segment")["Average_Order_Value"].mean()

Customer_Segment
Budget       44367.475513
Luxury       48157.249231
Mid-Range    45809.167442
Premium      41913.748062
Name: Average_Order_Value, dtype: float64

In [17]:
premium = data[data["Customer_Segment"]=="Premium"]["Average_Order_Value"]

budget = data[data["Customer_Segment"]=="Budget"]["Average_Order_Value"]

In [19]:
budget

0          432
4        54629
7       121417
9          866
13       30142
         ...
5115     15850
5118     53001
5133     17184
5142        58
5144     16105
Name: Average_Order_Value, Length: 1266, dtype: int64

In [18]:
premium

3         4416
6        74876
8        23093
19        4571
23       13856
         ...
5136      4147
5137    349637
5141      2617
5143     94881
5145    166575
Name: Average_Order_Value, Length: 1290, dtype: int64

In [20]:
t_stat, p_value = stats.ttest_ind(premium,budget,nan_policy="omit")

print("T Statistic:", t_stat)
print("P Value:", p_value)

T Statistic: -0.9499873137747873
P Value: 0.3422085832949139

In [21]:
if p_value < 0.05:
    print("Customer segments have significantly different order values.")
else:
    print("No significant difference found .")

No significant difference found.