In [1]:
import numpy as np
import pandas as pd

In [56]:
nm = pd.read_csv("/content/Retail_Dataset_Modified.csv")
nm

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [3]:
name = ["Sneh","Bhavya","Parth","Rehan","Uzair"]
pin = [104,102,106,109,110]
city = ["AHMEDABAD","SURAT","PUNE","NASHIK","PUNE"]

In [4]:
nm2 = {"NAME" : name , "PIN" : pin , "CITY" : city}
nm2

{'NAME': ['Sneh', 'Bhavya', 'Parth', 'Rehan', 'Uzair'],
 'PIN': [104, 102, 106, 109, 110],
 'CITY': ['AHMEDABAD', 'SURAT', 'PUNE', 'NASHIK', 'PUNE']}

In [5]:
nm5 = pd.DataFrame(nm2)
nm5

     NAME  PIN       CITY
0    Sneh  104  AHMEDABAD
1  Bhavya  102      SURAT
2   Parth  106       PUNE
3   Rehan  109     NASHIK
4   Uzair  110       PUNE

In [6]:
type(nm5)

pandas.core.frame.DataFrame

In [10]:
type(nm5["NAME"])
nm5["NAME"].ndim

1

In [11]:
nm5.ndim

2

In [12]:
nm5.head()

     NAME  PIN       CITY
0    Sneh  104  AHMEDABAD
1  Bhavya  102      SURAT
2   Parth  106       PUNE
3   Rehan  109     NASHIK
4   Uzair  110       PUNE

In [13]:
nm.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [14]:
nm.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [15]:
nm.sample(7)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
3896,BX_BANGALORE_088,BrandX_India Superstore Bangalore,BrandX_India,Express,Bangalore,Metro,White Sugar 1kg,Groceries,Sugar,Discontinued,...,81.2,87.0,Competitive,Low,7.0,105,4,2024,Q2,Summer
1400,BX_HYDERABAD_011,BrandX_India Apparel Hyderabad,BrandX_India,Flagship,Hyderabad,Metro,Zara Evening Dress,Clothes,Dresses,Mature,...,83.5,81.3,Competitive,Medium,7.0,87,11,2022,Q4,Winter
1599,BX_CHENNAI_058,BrandX_India Daily Chennai,BrandX_India,Express,Chennai,Metro,Brown Rice 1kg,Groceries,Rice,Declining,...,94.9,83.6,Competitive,Low,2.0,149,12,2022,Q4,Winter
1780,BX_LUCKNOW_022,BrandX_India Tech Hub Lucknow,BrandX_India,Express,Lucknow,Tier2,OnePlus 11,Electronics,Smartphones,Growing,...,68.1,66.5,Standard,Low,2.0,218,1,2023,Q1,Spring
2282,BX_BANGALORE_056,BrandX_India Apparel Bangalore,BrandX_India,Street Store,Bangalore,Metro,Pepe Jeans,Clothes,Jeans,Discontinued,...,76.4,85.2,Competitive,High,4.0,116,5,2023,Q2,Summer
1445,BX_BANGALORE_008,BrandX_India Comfort Bangalore,BrandX_India,Online Hub,Bangalore,Metro,Blue Star 1 Ton,Home Appliances,Air Conditioners,New Launch,...,80.4,86.9,Competitive,Low,2.0,694,11,2022,Q4,Winter
3121,BX_MUMBAI_071,BrandX_India Style Mumbai,BrandX_India,Mall Store,Mumbai,Metro,NaN,Clothes,Jeans,Discontinued,...,83.7,81.9,Competitive,Medium,7.0,96,11,2023,Q4,Winter

In [16]:
nm5.columns

Index(['NAME', 'PIN', 'CITY'], dtype='object')

In [17]:
nm.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [18]:
len(nm.columns)

47

In [19]:
nm5.isnull()

    NAME    PIN   CITY
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [20]:
nm5.isnull().sum()

NAME    0
PIN     0
CITY    0
dtype: int64

In [21]:
nm.isnull()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5167,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5168,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5169,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [22]:
nm.isnull().sum()

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [23]:
nm.isnull().sum() > 1

Store_ID                 False
Store_Name               False
Brand_Name               False
Store_Type               False
City                      True
City_Tier                False
Product_Name              True
Category                 False
Sub_Category             False
Product_Stage            False
Quantity_Available       False
Units_Sold               False
Unit_Price               False
Cost_Price               False
Revenue                   True
Profit_Margin            False
Average_Order_Value      False
Inventory_Turnover       False
Days_of_Stock            False
Customer_Segment         False
Sales_Channel            False
Payment_Method           False
Supplier                  True
Supplier_Rating          False
Promotion_Type           False
Promotion_Impact         False
Max_Discount_Offered     False
Return_Rate              False
Return_Reason            False
Customer_Satisfaction     True
Online_Rating            False
Review_Count             False
Sales_Rep_Experience     False
Sales_Rep_Rating         False
Market_Share             False
Competition_Level        False
Competitor_Count         False
Brand_Loyalty            False
Brand_Awareness          False
Price_Competitiveness    False
Weather_Impact           False
Delivery_Time             True
Shipping_Cost            False
Month                    False
Year                     False
Quarter                  False
Season                   False
dtype: bool

In [42]:
nm.loc[:, nm.isnull().sum() > 1]

,City,Product_Name,Revenue,Supplier,Customer_Satisfaction,Delivery_Time
0,Pune,Green Tea 100g,7320,BrandX_India E-commerce Hub,4.0,6.0
1,Mumbai,White Sugar 1kg,1645,BrandX_India Direct Import,3.9,4.0
2,Pune,Levi's T-Shirt,66340,BrandX_India Local Sourcing,4.3,4.0
3,Chennai,Adidas Hoodie,77748,BrandX_India Direct Import,4.4,5.0
4,Chennai,PlayStation 5,1976364,BrandX_India Local Sourcing,3.9,2.0
...,...,...,...,...,...,...
5166,Jaipur,Pepe Jeans,16611,BRANDX_INDIA LOCAL SOURCING,4.2,3.0
5167,Mumbai,White Sugar 1kg,2808,BRANDX_INDIA LOCAL SOURCING,3.7,7.0
5168,Kanpur,Dell XPS 13,982202,BRANDX_INDIA E-COMMERCE HUB,3.9,1.0
5169,Mumbai,Nike Air Max,244244,BRANDX_INDIA DIRECT IMPORT,4.4,3.0
5170,Delhi,MacBook Air M2,1408680,BRANDX_INDIA LOCAL SOURCING,4.7,3.0

In [27]:
nm.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [29]:
nm.loc[: , ['Brand_Name', 'City']]

        Brand_Name     City
0     BrandX_India     Pune
1     BrandX_India   Mumbai
2     BrandX_India     Pune
3     BrandX_India  Chennai
4     BrandX_India  Chennai
...            ...      ...
5166  BrandX_India  Jaipur
5167  BrandX_India  Mumbai
5168  BrandX_India  Kanpur
5169  BrandX_India  Mumbai
5170  BrandX_India   Delhi

[5171 rows x 2 columns]

In [31]:
nm.loc[3 , : ]

Store_ID                              BX_CHENNAI_061
Store_Name               BrandX_India Trends Chennai
Brand_Name                              BrandX_India
Store_Type                                Mall Store
City                                         Chennai
City_Tier                                      Metro
Product_Name                           Adidas Hoodie
Category                                     Clothes
Sub_Category                                 Jackets
Product_Stage                             New Launch
Quantity_Available                               163
Units_Sold                                        22
Unit_Price                                      3534
Cost_Price                                      2894
Revenue                                        77748
Profit_Margin                                  18.11
Average_Order_Value                             4416
Inventory_Turnover                              1.62
Days_of_Stock                                    222
Customer_Segment                             Premium
Sales_Channel                       BrandX_India App
Payment_Method                                  Card
Supplier                  BrandX_India Direct Import
Supplier_Rating                                  Nan
Promotion_Type                            Flash Sale
Promotion_Impact                                37.3
Max_Discount_Offered                              31
Return_Rate                                      4.0
Return_Reason                             Wrong Size
Customer_Satisfaction                            4.4
Online_Rating                                    5.0
Review_Count                                     221
Sales_Rep_Experience                               7
Sales_Rep_Rating                                 3.9
Market_Share                                    16.4
Competition_Level                               High
Competitor_Count                                  19
Brand_Loyalty                                   92.4
Brand_Awareness                                 88.0
Price_Competitiveness                    Competitive
Weather_Impact                                Medium
Delivery_Time                                    5.0
Shipping_Cost                                     79
Month                                              1
Year                                            2022
Quarter                                           Q1
Season                                        Spring
Name: 3, dtype: object

In [36]:
nm.loc[[3,7,9,1] , ['Online_Rating', 'Review_Count', 'Sales_Rep_Experience']]

   Online_Rating  Review_Count  Sales_Rep_Experience
3            5.0           221                     7
7            4.6           282                     6
9            4.7           222                     2
1            4.4           202                    10

In [37]:
nm.iloc[[5,7,1,3,17,19,35] , [3,8,5,1]]

      Store_Type Sub_Category City_Tier                      Store_Name
5   Street Store          Dal     Metro   BrandX_India Superstore Delhi
7     Mall Store      Laptops     Metro      BrandX_India Digital Delhi
1   Street Store        Sugar     Metro  BrandX_India Superstore Mumbai
3     Mall Store      Jackets     Metro     BrandX_India Trends Chennai
17    Mall Store          Oil     Metro    BrandX_India Daily Bangalore
19    Mall Store        Jeans     Metro       BrandX_India Style Mumbai
35      Flagship          Dal     Tier1    BrandX_India Daily Ahmedabad

In [38]:
nm.isnull().sum()

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [47]:
nm.loc[: , nm.isnull().sum() > 1 ].columns

Index(['City', 'Product_Name', 'Revenue', 'Supplier', 'Customer_Satisfaction',
       'Delivery_Time'],
      dtype='object')

In [57]:
nm.loc[: , nm.isnull().sum() == 68 ].columns

Index(['Supplier'], dtype='object')

In [48]:
nm.isnull().sum()

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [49]:
nm.shape

(5171, 47)

In [52]:
nm.dropna(inplace = True)

In [53]:
nm.shape

(4759, 47)

In [58]:
name2 = ["Sneh","Bhavya","","Parth","Rehan","Uzair"]
pin2 = [104,102,106,109,"",110]
city2 = ["AHMEDABAD","SURAT","PUNE","NASHIK","PUNE",""]

In [59]:
gh = pd.DataFrame({"NAME" : name2 , "PIN" : pin2 , "CITY" : city2})
gh

     NAME  PIN       CITY
0    Sneh  104  AHMEDABAD
1  Bhavya  102      SURAT
2          106       PUNE
3   Parth  109     NASHIK
4   Rehan            PUNE
5   Uzair  110

In [65]:
gh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    6 non-null      object
 1   PIN     6 non-null      object
 2   CITY    6 non-null      object
dtypes: object(3)
memory usage: 276.0+ bytes

In [60]:
gh.isnull().sum()

NAME    0
PIN     0
CITY    0
dtype: int64

In [61]:
name2 = ["Sneh","Bhavya",np.nan,"Parth","Rehan","Uzair"]
pin2 = [104,102,106,109,np.nan,110]
city2 = ["AHMEDABAD","SURAT","PUNE","NASHIK","PUNE",np.nan]

In [62]:
wr = pd.DataFrame({"NAME" : name2 , "PIN" : pin2 , "CITY" : city2})
wr

     NAME    PIN       CITY
0    Sneh  104.0  AHMEDABAD
1  Bhavya  102.0      SURAT
2     NaN  106.0       PUNE
3   Parth  109.0     NASHIK
4   Rehan    NaN       PUNE
5   Uzair  110.0        NaN

In [66]:
wr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    5 non-null      object
 1   PIN     5 non-null      float64
 2   CITY    5 non-null      object
dtypes: float64(1), object(2)
memory usage: 276.0+ bytes

In [64]:
wr.isnull().sum()

NAME    1
PIN     1
CITY    1
dtype: int64

In [67]:
wr.describe()

             PIN
count    5.00000
mean   106.20000
std      3.34664
min    102.00000
25%    104.00000
50%    106.00000
75%    109.00000
max    110.00000

In [68]:
wr.columns

Index(['NAME', 'PIN', 'CITY'], dtype='object')

In [69]:
wr["PIN"].mean()

np.float64(106.2)

In [70]:
wr["PIN"].median()

106.0

In [71]:
wr

     NAME    PIN       CITY
0    Sneh  104.0  AHMEDABAD
1  Bhavya  102.0      SURAT
2     NaN  106.0       PUNE
3   Parth  109.0     NASHIK
4   Rehan    NaN       PUNE
5   Uzair  110.0        NaN

In [72]:
wr["PIN"].fillna(wr["PIN"].mean())

0    104.0
1    102.0
2    106.0
3    109.0
4    106.2
5    110.0
Name: PIN, dtype: float64

In [73]:
wr["PIN"].fillna(wr["PIN"].median())

0    104.0
1    102.0
2    106.0
3    109.0
4    106.0
5    110.0
Name: PIN, dtype: float64