In [1]:
import numpy as np
import pandas as pd

In [2]:
dss = pd.read_csv("/content/Retail_Dataset_Modified.csv")
dss

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [3]:
dss.describe()

,Unit_Price,Cost_Price,Profit_Margin,Average_Order_Value,Inventory_Turnover,Days_of_Stock,Promotion_Impact,Max_Discount_Offered,Return_Rate,Customer_Satisfaction,...,Review_Count,Sales_Rep_Experience,Sales_Rep_Rating,Market_Share,Competitor_Count,Brand_Loyalty,Brand_Awareness,Delivery_Time,Month,Year
count,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5094.000000,...,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5171.000000,5111.000000,5171.000000,5171.000000
mean,36147.283117,28008.718236,22.455080,45000.251789,3.928517,142.718816,20.979791,22.679172,4.018294,4.209109,...,256.498936,5.548250,4.248018,15.406556,16.231483,81.351228,80.307097,3.984934,6.567588,2023.016438
std,53910.395954,41848.286241,4.349469,67405.809814,2.284159,128.281114,12.212204,15.784690,2.292903,0.280465,...,140.948535,2.861696,0.433274,6.009766,6.646939,8.018098,8.542352,2.021598,3.463351,0.814235
min,36.000000,28.000000,14.680000,41.000000,0.300000,32.000000,0.000000,0.000000,0.000000,3.600000,...,10.000000,1.000000,3.500000,3.000000,3.000000,67.000000,60.000000,1.000000,1.000000,2022.000000
25%,2016.500000,1548.500000,18.675000,2476.000000,2.220000,68.000000,13.100000,9.000000,2.000000,4.000000,...,138.000000,3.000000,3.900000,11.300000,11.000000,75.900000,77.700000,2.000000,4.000000,2022.000000
50%,11816.000000,9136.000000,22.450000,14734.000000,3.440000,105.000000,22.300000,22.000000,4.100000,4.200000,...,256.000000,6.000000,4.200000,14.900000,18.000000,80.400000,83.000000,4.000000,7.000000,2023.000000
75%,53778.500000,41569.000000,26.235000,66630.000000,5.260000,162.000000,31.200000,36.000000,6.000000,4.400000,...,378.000000,8.000000,4.600000,18.900000,22.000000,84.600000,86.600000,6.000000,10.000000,2024.000000
max,307651.000000,252171.000000,30.430000,450890.000000,11.100000,1200.000000,40.000000,50.000000,8.000000,4.900000,...,500.000000,10.000000,5.000000,30.000000,25.000000,100.000000,90.000000,7.000000,12.000000,2024.000000

In [4]:
dss.describe(include = "all")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
count,5171,5171,5171,5171,5109,5171,5098,5171,5171,5171,...,5171.000000,5171.000000,5171,5171,5111.000000,5171,5171.000000,5171.000000,5171,5171
unique,1179,280,4,5,51,3,53,20,25,5,...,NaN,NaN,3,3,NaN,542,NaN,NaN,4,4
top,BX_DELHI_004,BrandX_India Gadget Zone Delhi,BrandX_India,Mall Store,Delhi,Metro,H&M Cotton Tee,Electronics,T-Shirts,Growing,...,NaN,NaN,Competitive,Low,NaN,123,NaN,NaN,Q4,Monsoon
freq,20,78,5110,1065,1031,3580,137,1295,363,1094,...,NaN,NaN,2079,3755,NaN,60,NaN,NaN,1329,1720
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.351228,80.307097,NaN,NaN,3.984934,NaN,6.567588,2023.016438,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.018098,8.542352,NaN,NaN,2.021598,NaN,3.463351,0.814235,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.000000,60.000000,NaN,NaN,1.000000,NaN,1.000000,2022.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.900000,77.700000,NaN,NaN,2.000000,NaN,4.000000,2022.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.400000,83.000000,NaN,NaN,4.000000,NaN,7.000000,2023.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.600000,86.600000,NaN,NaN,6.000000,NaN,10.000000,2024.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,90.000000,NaN,NaN,7.000000,NaN,12.000000,2024.000000,NaN,NaN

In [5]:
dss.describe(include = "object")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Supplier,Supplier_Rating,Promotion_Type,Return_Reason,Competition_Level,Price_Competitiveness,Weather_Impact,Shipping_Cost,Quarter,Season
count,5171,5171,5171,5171,5109,5171,5098,5171,5171,5171,...,5103,5171,5171,5171,5171,5171,5171,5171,5171,5171
unique,1179,280,4,5,51,3,53,20,25,5,...,23,1,6,6,4,3,3,542,4,4
top,BX_DELHI_004,BrandX_India Gadget Zone Delhi,BrandX_India,Mall Store,Delhi,Metro,H&M Cotton Tee,Electronics,T-Shirts,Growing,...,BrandX_India Wholesale,Nan,BOGO,Changed Mind,High,Competitive,Low,123,Q4,Monsoon
freq,20,78,5110,1065,1031,3580,137,1295,363,1094,...,1055,5171,899,1036,2079,2079,3755,60,1329,1720

In [6]:
dss.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [7]:
dss.select_dtypes(include = "int")

,Unit_Price,Cost_Price,Average_Order_Value,Days_of_Stock,Max_Discount_Offered,Review_Count,Sales_Rep_Experience,Competitor_Count,Month,Year
0,305,239,432,156,9,53,5,8,1,2022
1,47,33,63,116,21,202,10,25,1,2022
2,2140,1715,2994,208,36,77,1,11,1,2022
3,3534,2894,4416,222,31,221,7,19,1,2022
4,50676,40467,54629,128,43,205,6,19,1,2022
...,...,...,...,...,...,...,...,...,...,...
5166,2373,1972,2617,797,48,368,6,7,11,2024
5167,54,43,58,93,13,424,3,21,7,2023
5168,75554,52990,94881,203,0,326,6,6,7,2023
5169,11102,9267,16105,224,30,73,1,17,12,2022
5170,117390,82950,166575,480,0,500,1,18,6,2024

In [8]:
dss["MINUSS"] = dss["Unit_Price"]-dss["Cost_Price"]
dss.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season', 'MINUSS'],
      dtype='object')

In [9]:
dss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
 47  MINUSS                 5171 non-null   int64
dtypes: float64(11), int64(11), object(26)
memory usage: 1.9+ MB

In [11]:
dss['Revenue'] = pd.to_numeric(dss['Revenue'], errors='coerce')
print("Mean:",dss["Revenue"].mean())
print("Median:" , dss["Revenue"].median())
print("Mode: " , dss["Revenue"].mode())

Mean: 1391139.6969161264
Median: 350064.0
Mode:  0    4465.0
1    4752.0
Name: Revenue, dtype: float64

In [12]:
dss.select_dtypes(include = "object")

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Supplier,Supplier_Rating,Promotion_Type,Return_Reason,Competition_Level,Price_Competitiveness,Weather_Impact,Shipping_Cost,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,BrandX_India E-commerce Hub,Nan,Festival Offer,Wrong Size,Medium,Standard,Low,57,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,BrandX_India Direct Import,Nan,Clearance,Poor Quality,High,Competitive,Low,99,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,BrandX_India Local Sourcing,Nan,Clearance,Wrong Size,Medium,Standard,Medium,101,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,BrandX_India Direct Import,Nan,Flash Sale,Wrong Size,High,Competitive,Medium,79,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,BrandX_India Local Sourcing,Nan,BOGO,Defective,High,Competitive,Low,110,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,BRANDX_INDIA LOCAL SOURCING,Nan,Discount,Poor Quality,Medium,Standard,Medium,150,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,BRANDX_INDIA LOCAL SOURCING,Nan,BOGO,Poor Quality,High,Competitive,Low,136,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,BRANDX_INDIA E-COMMERCE HUB,Nan,No Promotion,Poor Quality,Medium,Standard,Low,222,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,BRANDX_INDIA DIRECT IMPORT,Nan,BOGO,Changed Mind,High,Competitive,Medium,138,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,BRANDX_INDIA LOCAL SOURCING,Nan,No Promotion,Defective,High,Competitive,Low,210,Q2,Monsoon

In [16]:
dss.isnull().sum()

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  80
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
MINUSS                    0
dtype: int64

In [17]:
rt = pd.read_csv("/content/Retail_Dataset_Modified.csv")
rt["Shipping_Cost"] = pd.to_numeric(rt["Shipping_Cost"], errors='coerce').astype('Int64')
rt["Shipping_Cost"]

0        57
1        99
2       101
3        79
4       110
       ...
5166    150
5167    136
5168    222
5169    138
5170    210
Name: Shipping_Cost, Length: 5171, dtype: Int64

In [18]:
rt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5163 non-null   Int64
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: Int64(1), float64(11), int64(10), object(25)
memory usage: 1.9+ MB

In [19]:
we = pd.read_excel("/content/Sample-Superstore.xlsx")
we

/usr/local/lib/python3.13/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2015-110422,2015-01-21,2015-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2018-119914,2018-05-04,2018-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [21]:
we2 = we.select_dtypes(include= ["int" , "float"])

In [22]:
we2

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1      42420.0  261.9600         2      0.00   41.9136
1          2      42420.0  731.9400         3      0.00  219.5820
2          3      90036.0   14.6200         2      0.00    6.8714
3          4      33311.0  957.5775         5      0.45 -383.0310
4          5      33311.0   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990      33180.0   25.2480         3      0.20    4.1028
9990    9991      92627.0   91.9600         2      0.00   15.6332
9991    9992      92627.0  258.5760         2      0.20   19.3932
9992    9993      92627.0   29.6000         4      0.00   13.3200
9993    9994      92683.0  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [37]:
we2 = we.select_dtypes(include = "object")

In [23]:
we.to_csv("Samp_integer")

In [38]:
we2.to_csv("Samp2_Objj.csv")

In [39]:
we2.to_excel("Samp_Oj.xlsx")

In [ ]:
/content/Samp_integer

In [25]:
df = pd.read_csv("/content/Samp_integer")
df

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9989,9990,CA-2015-110422,2015-01-21,2015-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9990,9991,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9991,9992,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9992,9993,CA-2018-121258,2018-02-26,2018-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9993,9994,CA-2018-119914,2018-05-04,2018-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [34]:
vb = pd.read_csv("/content/ert.txt" , sep = " ")
vb["age"]

0    23
1    45
Name: age, dtype: int64

In [35]:
vb

   name  age       city
0  abcd   23  ahmedabad
1  xyzz   45      surat