In [2]:
import numpy as np
import pandas as pd

In [7]:
w = np.array([4,7,9,1])
m = np.array([[3,2,4,7] , [11,6,7,2]])
print("W:",w)
print("M:",m)
print("W DIM: " , w.ndim)
print("M DIM: " , m.ndim)
print("DTYPE : " , m.dtype)
print("TYPE : ", type(m))

W: [4 7 9 1]
M: [[ 3  2  4  7]
 [11  6  7  2]]
W DIM:  1
M DIM:  2
DTYPE :  int64
TYPE :  <class 'numpy.ndarray'>

In [9]:
print(m)
print("=========================")
print("SHAPE : " , m.shape)

[[ 3  2  4  7]
 [11  6  7  2]]
=========================
SHAPE :  (2, 4)

In [10]:
m = np.array([[3,2,4,7] , [11,6,7,2]] , ndmin = 5)
print("M:",m)
print("M DIM: " , m.ndim)

M: [[[[[ 3  2  4  7]
    [11  6  7  2]]]]]
M DIM:  5

In [11]:
m.shape

(1, 1, 1, 2, 4)

In [12]:
m.reshape(8,1)

array([[ 3],
       [ 2],
       [ 4],
       [ 7],
       [11],
       [ 6],
       [ 7],
       [ 2]])

In [13]:
m.reshape(1,8)

array([[ 3,  2,  4,  7, 11,  6,  7,  2]])

In [14]:
m.reshape(8,)

array([ 3,  2,  4,  7, 11,  6,  7,  2])

In [15]:
m.reshape(2,8)

ValueError: cannot reshape array of size 8 into shape (2,8)

In [17]:
print("(2,4): ",m.reshape(2,4))
print("============================")
print("(4,2): ",m.reshape(4,2))

(2,4):  [[ 3  2  4  7]
 [11  6  7  2]]
============================
(4,2):  [[ 3  2]
 [ 4  7]
 [11  6]
 [ 7  2]]

In [18]:
m

array([[[[[ 3,  2,  4,  7],
          [11,  6,  7,  2]]]]])

In [19]:
import numpy as np
import pandas as pd

In [20]:
ty = pd.read_csv("/content/Retail_Dataset_Modified.csv")
ty

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [21]:
ty.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [22]:
ty.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [24]:
ty.sample(5)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
358,BX_AHMEDABAD_021,BrandX_India Electronics Ahmedabad,BrandX_India,Street Store,Ahmedabad,Tier1,Sony WH-1000XM5,Electronics,Headphones,Growing,...,67.1,77.4,Competitive,Low,6.0,157,3,2022,Q1,Summer
251,BX_MUMBAI_039,BrandX_India Electronics Mumbai,BrandX_India,Express,Mumbai,Metro,HP Pavilion,Electronics,Laptops,New Launch,...,75.3,81.1,Aggressive,Low,1.0,192,2,2022,Q1,Spring
717,BX_JAIPUR_069,BrandX_India Tech Hub Jaipur,BrandX_India,Online Hub,Jaipur,Tier2,Samsung Tab S8,Electronics,Tablets,Declining,...,83.0,62.5,Standard,Low,2.0,234,6,2022,Q2,Monsoon
4038,BX_MUMBAI_038,BrandX_India Accessories Mumbai,BrandX_India,Online Hub,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,81.6,83.7,Competitive,Low,3.0,116,5,2024,Q2,Summer
3239,BX_MUMBAI_059,BrandX_India Digital Mumbai,BrandX_India,Online Hub,Mumbai,Metro,iPhone 14,Electronics,Smartphones,Mature,...,90.0,82.0,Competitive,Low,4.0,183,12,2023,Q4,Winter

In [25]:
ty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   object
 1   Store_Name             5171 non-null   object
 2   Brand_Name             5171 non-null   object
 3   Store_Type             5171 non-null   object
 4   City                   5109 non-null   object
 5   City_Tier              5171 non-null   object
 6   Product_Name           5098 non-null   object
 7   Category               5171 non-null   object
 8   Sub_Category           5171 non-null   object
 9   Product_Stage          5171 non-null   object
 10  Quantity_Available     5171 non-null   object
 11  Units_Sold             5171 non-null   object
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   object
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   object
 20  Sales_Channel          5171 non-null   object
 21  Payment_Method         5171 non-null   object
 22  Supplier               5103 non-null   object
 23  Supplier_Rating        5171 non-null   object
 24  Promotion_Type         5171 non-null   object
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   object
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   object
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   object
 40  Weather_Impact         5171 non-null   object
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   object
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   object
 46  Season                 5171 non-null   object
dtypes: float64(11), int64(10), object(26)
memory usage: 1.9+ MB

In [26]:
ty.isnull().sum()

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [27]:
ty.isnull().sum().sum()

np.int64(412)

In [28]:
ty.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring

In [29]:
ty.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='object')

In [31]:
ty["City"].value_counts()

City
Delhi            1031
Mumbai            980
Bangalore         512
Chennai           485
Hyderabad         470
Pune              272
Jaipur            268
Ahmedabad         254
Surat             232
Bhopal            113
Nagpur            111
Visakhapatnam     106
Kanpur             98
Lucknow            92
Mumbai              8
MUMBAI              7
Delhi               7
delhi               6
CHENNAI             4
chennai             4
  Mumbai            4
  Chennai           3
  Delhi             3
Chennai             3
  Jaipur            3
jaipur              2
AHMEDABAD           2
  Kanpur            2
  Hyderabad         2
Jaipur              2
mumbai              2
  Surat             2
KANPUR              1
JAIPUR              1
NAGPUR              1
ahmedabad           1
hyderabad           1
bhopal              1
HYDERABAD           1
lucknow             1
BANGALORE           1
pune                1
  Pune              1
SURAT               1
BHOPAL              1
bangalore           1
Ahmedabad           1
Hyderabad           1
Bangalore           1
KANPUR              1
Kanpur              1
Name: count, dtype: int64

In [33]:
ty["City_2"] = ty["City"].replace({"pune" : "Pune"})

In [34]:
ty.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season', 'City_2'],
      dtype='object')

In [38]:
ty["City_2"].value_counts()

City_2
Delhi            1031
Mumbai            980
Bangalore         512
Chennai           485
Hyderabad         470
Pune              273
Jaipur            268
Ahmedabad         254
Surat             232
Bhopal            113
Nagpur            111
Visakhapatnam     106
Kanpur             98
Lucknow            92
Mumbai              8
MUMBAI              7
Delhi               7
delhi               6
  Mumbai            4
chennai             4
CHENNAI             4
  Chennai           3
  Delhi             3
Chennai             3
  Jaipur            3
jaipur              2
  Kanpur            2
AHMEDABAD           2
mumbai              2
  Hyderabad         2
Jaipur              2
  Surat             2
KANPUR              1
NAGPUR              1
HYDERABAD           1
hyderabad           1
lucknow             1
bhopal              1
JAIPUR              1
BANGALORE           1
ahmedabad           1
  Pune              1
SURAT               1
BHOPAL              1
bangalore           1
Ahmedabad           1
Hyderabad           1
Bangalore           1
KANPUR              1
Kanpur              1
Name: count, dtype: int64

In [41]:
ty["City_2"] = ty["City"].replace({"pune" : "Pune" , "KANPUR" : "Kanpur"})

In [42]:
ty["City_2"].value_counts()

City_2
Delhi            1031
Mumbai            980
Bangalore         512
Chennai           485
Hyderabad         470
Pune              273
Jaipur            268
Ahmedabad         254
Surat             232
Bhopal            113
Nagpur            111
Visakhapatnam     106
Kanpur             99
Lucknow            92
Mumbai              8
MUMBAI              7
Delhi               7
delhi               6
  Mumbai            4
CHENNAI             4
chennai             4
  Delhi             3
Chennai             3
  Chennai           3
  Jaipur            3
AHMEDABAD           2
jaipur              2
  Kanpur            2
  Hyderabad         2
mumbai              2
  Surat             2
Jaipur              2
BANGALORE           1
HYDERABAD           1
hyderabad           1
lucknow             1
bhopal              1
JAIPUR              1
NAGPUR              1
ahmedabad           1
  Pune              1
SURAT               1
BHOPAL              1
bangalore           1
Ahmedabad           1
Hyderabad           1
Bangalore           1
KANPUR              1
Kanpur              1
Name: count, dtype: int64

In [43]:
for j in ty["City"]:
  print(j)

Pune
Mumbai
Pune
Chennai
Chennai
Delhi
Mumbai
Delhi
Mumbai
Nagpur
Mumbai
Delhi
Delhi
Delhi
Nagpur
Bangalore
Delhi
Bangalore
Hyderabad
Mumbai
Delhi
Mumbai
Mumbai
Pune
Delhi
Chennai
Mumbai
nan
Bhopal
Visakhapatnam
Mumbai
Surat
Jaipur
Mumbai
Mumbai
Ahmedabad
Bangalore
Mumbai
Delhi
Mumbai
Mumbai
Bangalore
Bangalore
Bangalore
Delhi
Mumbai
Surat
Surat
Chennai
Jaipur
Kanpur
Delhi
Mumbai
Delhi
Mumbai
Mumbai
Mumbai
Mumbai
Surat
Mumbai
Visakhapatnam
Hyderabad
Delhi
Surat
Visakhapatnam
Mumbai
Pune
Bhopal
Chennai
Bangalore
Bhopal
Chennai
Ahmedabad
Hyderabad
Delhi
Chennai
Bangalore
Delhi
Hyderabad
Mumbai
Bangalore
Bangalore
Hyderabad
Mumbai
CHENNAI
Delhi
Bangalore
Bangalore
Mumbai
Delhi
Mumbai
Hyderabad
Hyderabad
Visakhapatnam
Mumbai
Mumbai
Bangalore
Chennai
Pune
Bangalore
Mumbai
Jaipur
Mumbai
Delhi
Chennai
Surat
Delhi
Hyderabad
Mumbai
Delhi
Jaipur
Mumbai
Mumbai
Bangalore
Hyderabad
Jaipur
Hyderabad
Mumbai
Delhi
Kanpur
Mumbai
Visakhapatnam
Surat
Ahmedabad
Delhi
Mumbai
Delhi
Chennai
Chennai
Ahmedabad
Jaipur
Bhopal
Nagpur
Bangalore
Delhi
Chennai
Delhi
Ahmedabad
nan
Chennai
Visakhapatnam
Bangalore
Pune
Mumbai
Bangalore
Pune
Mumbai
Kanpur
Nagpur
Mumbai
Bangalore
Mumbai
Bangalore
Mumbai
Pune
Mumbai
nan
Hyderabad
Pune
Lucknow
Delhi
Bangalore
Bangalore
Visakhapatnam
Jaipur
Delhi
Ahmedabad
Delhi
Mumbai
Ahmedabad
Delhi
Bhopal
Bangalore
Ahmedabad
Bangalore
Delhi
Surat
Surat
Bangalore
Delhi
Hyderabad
Bangalore
Jaipur
Lucknow
Mumbai
Hyderabad
Delhi
Bangalore
Bangalore
Delhi
Chennai
Mumbai
Mumbai
Jaipur
Hyderabad
Delhi
Jaipur
Delhi
Pune
Chennai
Bangalore
Lucknow
Mumbai
Hyderabad
Bangalore
Bangalore
Delhi
Ahmedabad
Delhi
Chennai
Bangalore
Kanpur
Delhi
nan
Surat
Ahmedabad
Mumbai
Jaipur
Lucknow
Mumbai
Chennai
Delhi
Chennai
Delhi
Delhi
Delhi
Delhi
Mumbai
Mumbai
Hyderabad
Delhi
Jaipur
Ahmedabad
Hyderabad
Lucknow
Mumbai
Delhi
Hyderabad
Delhi
Hyderabad
Hyderabad
Delhi
Hyderabad
Delhi
Visakhapatnam
Ahmedabad
Ahmedabad
Hyderabad
Hyderabad
Delhi
Hyderabad
Mumbai
Mumbai
Hyderabad
Delhi
Bangalore
Delhi
Hyderabad
Pune
Mumbai
Bangalore
Bangalore
Delhi
Delhi
Delhi
Bangalore
Ahmedabad
Mumbai
Chennai
Delhi
Ahmedabad
Delhi
Mumbai
Kanpur
Hyderabad
Bangalore
Bangalore
Chennai
Mumbai
Hyderabad
Hyderabad
Delhi
Surat
Delhi
Hyderabad
Mumbai
Pune
Jaipur
Chennai
Chennai
Delhi
Jaipur
Mumbai
Mumbai
Bangalore
Jaipur
Bangalore
Mumbai
Delhi
Delhi
Pune
nan
jaipur
Hyderabad
Chennai
Delhi
Ahmedabad
Jaipur
Delhi
Bhopal
Mumbai
Delhi
Mumbai
Delhi
Mumbai
Delhi
Delhi
Mumbai
Bangalore
Delhi
Chennai
Delhi
Bangalore
Bangalore
Delhi
Jaipur
Mumbai
Hyderabad
Ahmedabad
Delhi
Chennai
Bangalore
Jaipur
Mumbai
Chennai
Bangalore
Delhi
Mumbai
Hyderabad
Chennai
Bangalore
Mumbai
Bhopal
Pune
Bangalore
Mumbai
Bhopal
Bangalore
Bangalore
Jaipur
Nagpur
Chennai
Chennai
Jaipur
Chennai
Delhi
Bangalore
Mumbai
Ahmedabad
Mumbai
Delhi
Chennai
Pune
Bangalore
Delhi
AHMEDABAD
Lucknow
Bangalore
Bangalore
Surat
Delhi
Mumbai
Bhopal
Mumbai
Delhi
Pune
Chennai
Mumbai
Delhi
Chennai
Delhi
Hyderabad
Pune
Mumbai
Kanpur
Bhopal
Bangalore
Jaipur
Nagpur
Bangalore
Chennai
Chennai
Surat
Ahmedabad
Surat
Chennai
Bangalore
Mumbai
Delhi
Delhi
Mumbai
Surat
Visakhapatnam
Bangalore
Bangalore
Delhi
Surat
Delhi
Hyderabad
Mumbai
Chennai
Ahmedabad
Mumbai
Kanpur
Pune
Kanpur
Chennai
Delhi
Pune
Ahmedabad
Pune
Bangalore
Chennai
Mumbai
Mumbai
Chennai
Mumbai
Mumbai
Chennai
Pune
Delhi
Nagpur
Mumbai
Mumbai
Chennai
Delhi
Delhi
nan
Delhi
Jaipur
Chennai
Jaipur
Lucknow
Mumbai
Ahmedabad
Bangalore
Chennai
Delhi
Hyderabad
Surat
Delhi
Chennai
Surat
Mumbai
Pune
Delhi
Hyderabad
Surat
Mumbai
Pune
Pune
Hyderabad
Mumbai
Chennai
Hyderabad
Delhi
Hyderabad
Nagpur
Chennai
Pune
Delhi
Delhi
Mumbai
Mumbai
Ahmedabad
Hyderabad
Delhi
Surat
Delhi
Jaipur
Surat
Delhi
Delhi
Delhi
Chennai
Delhi
Kanpur
Mumbai
Delhi
Delhi
Bangalore
Delhi
Bhopal
Delhi
Hyderabad
Delhi
Mumbai
Mumbai
Mumbai
Hyderabad
Mumbai
Hyderabad
Jaipur
Mumbai
Chennai
Ahmedabad
Jaipur
Hyderabad
Delhi
Bangalore
Jaipur
Delhi
Delhi
Pune
Mumbai
Chennai
Bhopal
Hyderabad
Mumbai
Delhi
Hyderabad
Chennai
Delhi
Delhi
Delhi
Mumbai
Hyderabad
Delhi
Pune
Delhi
Pune
Bangalore
Pune
Jaipur
Pune
Chennai
Visakhapatnam
Hyderabad
Delhi
Chennai
Delhi
Hyderabad
Ahmedabad
Pune
Mumbai
Hyderabad
Chennai
Delhi
Delhi
Mumbai
Mumbai
Mumbai
Ahmedabad
Bangalore
Chennai
Bangalore
Jaipur
Chennai
Lucknow
Delhi
Mumbai
Mumbai
Delhi
Mumbai
Ahmedabad
Bangalore
Mumbai
Bangalore
Mumbai
Kanpur
Delhi
Pune
Jaipur
Bangalore
Bangalore
Delhi
Surat
Chennai
Bangalore
Bangalore
Surat
Delhi
Pune
Delhi
Ahmedabad
Bangalore
Delhi
Hyderabad
Hyderabad
Delhi
Mumbai
Pune
Chennai
Delhi
Pune
Ahmedabad
Mumbai
  Kanpur
Delhi
Bangalore
Bangalore
Mumbai
Jaipur
Nagpur
nan
Delhi
Mumbai
Chennai
Surat
Hyderabad
Chennai
Chennai
Mumbai
Kanpur
Delhi
Surat
Bhopal
Mumbai
Bangalore
Pune
Nagpur
Nagpur
Ahmedabad
Mumbai
Delhi
Lucknow
Mumbai
Mumbai
Pune
Chennai
Ahmedabad
Hyderabad
Mumbai
Jaipur
Mumbai
Hyderabad
Nagpur
Chennai
Jaipur
Mumbai
Chennai
Delhi
Lucknow
Mumbai
Delhi
Mumbai
Bangalore
Delhi
Pune
Delhi
Ahmedabad
Mumbai
Delhi
Hyderabad
Pune
Ahmedabad
Mumbai
Mumbai
  Delhi
Hyderabad
Mumbai
Bhopal
Delhi
Mumbai
Delhi
Jaipur
Hyderabad
Ahmedabad
Mumbai
Surat
Mumbai
Bhopal
Mumbai
MUMBAI
Surat
Jaipur
Mumbai
Hyderabad
Jaipur
Jaipur
Ahmedabad
Delhi
Mumbai
Hyderabad
BANGALORE
Delhi
Pune
Mumbai
Delhi
Delhi
Jaipur
Chennai
Mumbai
Ahmedabad
Jaipur
Chennai
Jaipur
Pune
Bangalore
Delhi
Delhi
Bangalore
Delhi
NAGPUR
Kanpur
Jaipur
Bangalore
Delhi
Delhi
Delhi
Visakhapatnam
Pune
Delhi
Chennai
nan
Surat
Delhi
Jaipur
Mumbai
Delhi
Chennai
Ahmedabad
Ahmedabad
Mumbai
Mumbai
Nagpur
Surat
Mumbai
nan
Surat
Mumbai
Pune
Nagpur
Kanpur
Delhi
Delhi
Hyderabad
Bangalore
Mumbai
Mumbai
Lucknow
Hyderabad
Pune
Surat
Mumbai
Bangalore
Mumbai
Hyderabad
Delhi
Chennai
Delhi
Delhi
Mumbai
Bangalore
Mumbai
Ahmedabad
Pune
Delhi
Bangalore
Mumbai
Kanpur
Bangalore
Pune
Hyderabad
Bangalore
Delhi
Chennai
Mumbai
Bangalore
Ahmedabad
Pune
Mumbai
Bangalore
Nagpur
Jaipur
Visakhapatnam
Mumbai
Delhi
Jaipur
Jaipur
Bangalore
Mumbai
Kanpur
Mumbai
Chennai
Chennai
Surat
Bangalore
Jaipur
Mumbai
Mumbai
Delhi
Mumbai
Kanpur
Chennai
Delhi
Mumbai
Bangalore
Bangalore
Mumbai
Delhi
Hyderabad
Bangalore
Ahmedabad
Mumbai
Delhi
Bangalore
Bangalore
Delhi
Surat
Mumbai
Bangalore
Ahmedabad
Surat
Chennai
Jaipur
Mumbai
Chennai
Jaipur
Delhi
MUMBAI
Delhi
Hyderabad
Chennai
Jaipur
Jaipur
Surat
Ahmedabad
Delhi
Delhi
Chennai
Mumbai
Jaipur
Bhopal
Bangalore
Chennai
Bhopal
Mumbai
Mumbai
Mumbai
Pune
Mumbai
Delhi
Mumbai
Surat
Ahmedabad
Ahmedabad
Pune
Hyderabad
Delhi
Delhi
Mumbai
Hyderabad
Hyderabad
Hyderabad
Mumbai
Bangalore
Chennai
Bhopal
Mumbai
Nagpur
Kanpur
Bangalore
Surat
Mumbai
Mumbai
delhi
Pune
Mumbai
Nagpur
Delhi
Kanpur
Ahmedabad
Delhi
Mumbai
Mumbai
Jaipur
Bhopal
Ahmedabad
Jaipur
Nagpur
Delhi
Hyderabad
Mumbai
Mumbai
Jaipur
Bangalore
Jaipur
Pune
Ahmedabad
Ahmedabad
Delhi
Mumbai
Mumbai
Mumbai
Mumbai
Delhi
Pune
Mumbai
Bangalore
Ahmedabad
Delhi
Hyderabad
Hyderabad
Mumbai
Hyderabad
Bhopal
Mumbai
Delhi
Delhi
Surat
Pune
Ahmedabad
  Chennai
Delhi
Mumbai
Chennai
Delhi
Delhi
Bangalore
Hyderabad
Delhi
Delhi
Lucknow
Mumbai
Delhi
Hyderabad
Delhi
Mumbai
Delhi
Mumbai
Delhi
Lucknow
Jaipur
Delhi
Mumbai
Delhi
Chennai
Mumbai
Bangalore
Bhopal
Hyderabad
Delhi
Bangalore
Lucknow
Kanpur
Chennai
Mumbai
nan
Mumbai
Delhi
Pune
Bhopal
Surat
Delhi
Chennai
Delhi
Kanpur
Kanpur
Jaipur
Pune
Mumbai
Mumbai
Delhi
Mumbai
Hyderabad
Bangalore
Hyderabad
Chennai
Delhi
Mumbai
Delhi
Visakhapatnam
Chennai
Delhi
Ahmedabad
Mumbai
Chennai
Hyderabad
Mumbai
Delhi
Ahmedabad
Jaipur
Delhi
Surat
Visakhapatnam
Kanpur
Mumbai
Jaipur
Ahmedabad
Delhi
Nagpur
Chennai
Pune
Delhi
Mumbai
Delhi
Hyderabad
Bangalore
Mumbai
Mumbai
Mumbai
Chennai
Surat
Mumbai
Surat
Chennai
Hyderabad
Visakhapatnam
Mumbai
Chennai
Bangalore
Bhopal
Delhi
Hyderabad
Mumbai
Delhi
Ahmedabad
Chennai
Delhi
Chennai
Mumbai
Mumbai
Delhi
Mumbai
Bangalore
Delhi
Delhi
Delhi
Chennai
Mumbai
Mumbai
nan
Bhopal
Mumbai
Jaipur
Chennai
Mumbai
Chennai
Bangalore
Bangalore
Mumbai
Bangalore
Ahmedabad
Surat
Chennai
Bangalore
Mumbai
Jaipur
Pune
Mumbai
Delhi
Ahmedabad
Mumbai
Jaipur
Delhi
Lucknow
Mumbai
Hyderabad
Mumbai
Hyderabad
Visakhapatnam
Delhi
Bangalore
Mumbai
Bangalore
Mumbai
Hyderabad
Hyderabad
Delhi
Mumbai
Surat
Delhi
Hyderabad
Surat
Bangalore
Chennai
Bangalore
Mumbai
Pune
Hyderabad
Bhopal
Bangalore
Ahmedabad
Bangalore
Chennai
Delhi
Bangalore
nan
Pune
Ahmedabad
Mumbai
Hyderabad
Mumbai
Mumbai
Bangalore
Delhi
Ahmedabad
Ahmedabad
Hyderabad
Mumbai
Hyderabad
Hyderabad
Mumbai
Delhi
Mumbai
Bhopal
Delhi
Nagpur
Delhi
Delhi
Delhi
Delhi
Visakhapatnam
Visakhapatnam
Mumbai
Jaipur
Hyderabad
Delhi
Jaipur
Jaipur
Mumbai
Hyderabad
Kanpur
Delhi
Hyderabad
Chennai
Bangalore
Mumbai
Hyderabad
Ahmedabad
Mumbai
Mumbai
Delhi
Visakhapatnam
Delhi
Surat
Lucknow
Lucknow
Bangalore
Bangalore
Ahmedabad
Ahmedabad
Mumbai
Kanpur
Delhi
Delhi
Mumbai
Delhi
Chennai
Delhi
Ahmedabad
Pune
Mumbai
Hyderabad
Surat
Delhi
Chennai
Mumbai
Visakhapatnam
Bhopal
Bangalore
Pune
Jaipur
Delhi
Mumbai
Mumbai
Bangalore
Jaipur
Chennai
Ahmedabad
Surat
Delhi
Delhi
Bangalore
nan
Delhi
Delhi
Delhi
Hyderabad
Mumbai
Bangalore
nan
Surat
Mumbai
Hyderabad
Mumbai
Ahmedabad
Bhopal
Chennai
Bangalore
Delhi
Bangalore
Mumbai
Surat
Mumbai
Delhi
Bangalore
Delhi
Ahmedabad
Hyderabad
Chennai
Mumbai
Delhi
Delhi
Jaipur
Mumbai
Mumbai
Delhi
Mumbai
Jaipur
Bangalore
Delhi
nan
Delhi
Mumbai
Surat
Chennai
Ahmedabad
Bangalore
Ahmedabad
Chennai
Mumbai
Mumbai
Delhi
Ahmedabad
Mumbai
Delhi
Visakhapatnam
Surat
Chennai
Mumbai
Mumbai
Chennai
Kanpur
Ahmedabad
Delhi
Hyderabad
Bangalore
Surat
Mumbai
Jaipur
Delhi
Pune
Delhi
Delhi
Mumbai
Hyderabad
Visakhapatnam
Bangalore
Nagpur
Chennai
Pune
Bhopal
Lucknow
Delhi
Chennai
Chennai
Mumbai
Surat
Bangalore
Jaipur
Delhi
Delhi
Bangalore
Delhi
Surat
Delhi
Pune
Surat
Delhi
Pune
Mumbai
Hyderabad
Surat
Bangalore
Ahmedabad
Pune
Delhi
Chennai
Delhi
Bangalore
Bangalore
Hyderabad
Mumbai
Hyderabad
nan
Mumbai
Delhi
Jaipur
Kanpur
Bhopal
Mumbai
Delhi
Bhopal
Hyderabad
Delhi
Mumbai
Bangalore
Jaipur
Mumbai
Delhi
Ahmedabad
Surat
Delhi
Chennai
Bhopal
Chennai
Jaipur
Mumbai
Mumbai
Mumbai
Delhi
Surat
Chennai
Pune
Delhi
Ahmedabad
Jaipur
Surat
Hyderabad
KANPUR
Bangalore
Pune
Mumbai
Jaipur
Surat
Delhi
Delhi
Jaipur
Delhi
Pune
nan
Mumbai
Chennai
Ahmedabad
Chennai
Hyderabad
Hyderabad
Delhi
Delhi
Bhopal
Pune
Delhi
Pune
Delhi
Bangalore
Ahmedabad
delhi
Chennai
Mumbai
Mumbai
Jaipur
Hyderabad
Chennai
Bangalore
Mumbai
Pune
Delhi
Chennai
Chennai
Hyderabad
Pune
Bangalore
Pune
Chennai
Mumbai
Delhi
Mumbai
Hyderabad
Delhi
Delhi
Surat
Chennai
Mumbai
Mumbai
Surat
Bangalore
Surat
Hyderabad
Chennai
Jaipur
Bangalore
Nagpur
Pune
Jaipur
Delhi
Delhi
Pune
Mumbai
Chennai
Hyderabad
Nagpur
Mumbai
Mumbai
Mumbai
Ahmedabad
Delhi
Mumbai
Delhi
Hyderabad
Mumbai
Delhi
Mumbai
Surat
Hyderabad
Delhi
Kanpur
Delhi
Mumbai
Surat
Delhi
Delhi
Lucknow
Hyderabad
Mumbai
Delhi
Ahmedabad
Delhi
Lucknow
Pune
Bangalore
Delhi
Delhi
Pune
Lucknow
Surat
Bangalore
Hyderabad
Delhi
Nagpur
Bangalore
Bangalore
Delhi
  Surat
Chennai
Delhi
Mumbai
Mumbai
Delhi
Bhopal
Delhi
Hyderabad
Delhi
Chennai
Bangalore
Delhi
Hyderabad
Nagpur
Hyderabad
Nagpur
Chennai
Delhi
nan
Nagpur
Hyderabad
Visakhapatnam
Hyderabad
Mumbai
Mumbai
Mumbai
Delhi
Mumbai
Chennai
Bangalore
Delhi
Lucknow
Kanpur
Chennai
Mumbai
Delhi
Chennai
Delhi
Visakhapatnam
Pune
Kanpur
Mumbai
Chennai
Mumbai
Ahmedabad
Chennai
Ahmedabad
Kanpur
Mumbai
Delhi
Jaipur
Pune
Bangalore
Delhi
Delhi
Bangalore
Surat
Mumbai
Delhi
Bangalore
Jaipur
Hyderabad
Delhi
Ahmedabad
Chennai
Pune
Ahmedabad
Hyderabad
Bangalore
Mumbai
Mumbai
Bhopal
Visakhapatnam
Bangalore
Mumbai
Mumbai
Mumbai
Pune
Mumbai
Delhi
Nagpur
Mumbai
Mumbai
Mumbai
Surat
Pune
Delhi
Visakhapatnam
Surat
Hyderabad
Mumbai
Mumbai
Mumbai
Delhi
Bangalore
Mumbai
Bangalore
Hyderabad
Hyderabad
Kanpur
Mumbai
Surat
Chennai
Bangalore
Delhi
Pune
Bangalore
Delhi
Jaipur
Delhi
Hyderabad
Delhi
Hyderabad
Hyderabad
Chennai
Bangalore
Delhi
Visakhapatnam
Delhi
Mumbai
Pune
Bangalore
Mumbai
Mumbai
Delhi
Delhi
Pune
Bhopal
Lucknow
Hyderabad
Bangalore
Hyderabad
Mumbai
Hyderabad
JAIPUR
Hyderabad
Mumbai
Mumbai
Delhi
Pune
Delhi
Jaipur
Mumbai
Chennai
Pune
Jaipur
Chennai
nan
Mumbai
Lucknow
Mumbai
Jaipur
Delhi
Jaipur
Hyderabad
Mumbai
Kanpur
Hyderabad
Delhi
Hyderabad
Mumbai
Bangalore
Lucknow
Ahmedabad
Chennai
Delhi
Kanpur
Mumbai
Chennai
Mumbai
Mumbai
Nagpur
Visakhapatnam
Chennai
Chennai
Delhi
Bangalore
Bhopal
Bangalore
Surat
Chennai
Lucknow
Chennai
Delhi
Mumbai
Delhi
Chennai
Mumbai
Hyderabad
Mumbai
Delhi
Delhi
Mumbai
Mumbai
Bangalore
Pune
Bangalore
Bangalore
Pune
Pune
Pune
Chennai
Hyderabad
Surat
Hyderabad
Delhi
Surat
Kanpur
Delhi
Delhi
Bangalore
Chennai
Mumbai
Bangalore
Delhi
Hyderabad
Mumbai
Kanpur
Delhi
Jaipur
Delhi
Nagpur
Pune
Hyderabad
Delhi
Bangalore
Mumbai
Hyderabad
Delhi
Pune
Delhi
Bhopal
Jaipur
Hyderabad
Mumbai
Jaipur
Chennai
Mumbai
Delhi
Delhi
Pune
Kanpur
Delhi
Surat
Hyderabad
Mumbai
Mumbai
Mumbai
Mumbai
Bhopal
Delhi
Delhi
Jaipur
Delhi
Bangalore
Jaipur
Delhi
Surat
Hyderabad
Mumbai
Kanpur
Mumbai
Chennai
Bhopal
Mumbai
Bhopal
Pune
Mumbai
Delhi
Mumbai
Mumbai
Chennai
Mumbai
Delhi
Chennai
Surat
Delhi
Visakhapatnam
Chennai
lucknow
Delhi
Delhi
Mumbai
Delhi
Mumbai
Mumbai
Ahmedabad
Jaipur
nan
Mumbai
Mumbai
Chennai
Surat
Jaipur
Delhi
Hyderabad
Chennai
Delhi
Mumbai
Bangalore
Delhi
Mumbai
Mumbai
Delhi
nan
Bangalore
Hyderabad
Chennai
Surat
Visakhapatnam
Chennai
Delhi
Mumbai
Delhi
nan
Delhi
Mumbai
Pune
Mumbai
nan
Lucknow
Mumbai
Delhi
Chennai
Bangalore
Delhi
Chennai
Hyderabad
Jaipur
Bangalore
Chennai
Delhi
Bangalore
Hyderabad
Delhi
Delhi
Visakhapatnam
Mumbai
Delhi
nan
Surat
Delhi
Pune
Mumbai
Mumbai
Lucknow
Jaipur
Visakhapatnam
Delhi
Mumbai
jaipur
Jaipur
Chennai
Lucknow
Lucknow
Mumbai
Bangalore
Surat
Pune
Delhi
Mumbai
Jaipur
Mumbai
Delhi
Visakhapatnam
Delhi
Mumbai
Mumbai
Delhi
Mumbai
Hyderabad
Jaipur
Delhi
Mumbai
Delhi
nan
Mumbai
Kanpur
Chennai
Mumbai
Mumbai
Hyderabad
Chennai
Mumbai
Chennai
Delhi
Delhi
Kanpur
Hyderabad
Nagpur
Delhi
Chennai
Surat
Mumbai
Hyderabad
Chennai
Chennai
Bangalore
Bhopal
Lucknow
Chennai
Bangalore
Mumbai
Hyderabad
Hyderabad
Delhi
Delhi
Mumbai
Delhi
Delhi
Surat
Jaipur
Hyderabad
Hyderabad
Delhi
Pune
Ahmedabad
Mumbai
Pune
Lucknow
Jaipur
Chennai
Surat
Mumbai
Mumbai
Chennai
Bangalore
Delhi
Mumbai
Delhi
Bangalore
Mumbai
Bangalore
Lucknow
Bangalore
Lucknow
Delhi
Mumbai
Mumbai
Mumbai
Pune
Mumbai
Jaipur
Delhi
Delhi
Visakhapatnam
Chennai
Lucknow
Mumbai
Jaipur
Delhi
Hyderabad
Bangalore
Chennai
Chennai
Bangalore
Delhi
Delhi
Mumbai
Hyderabad
Mumbai
Ahmedabad
Nagpur
Bhopal
Surat
Mumbai
Bangalore
Ahmedabad
Bangalore
Pune
Surat
Ahmedabad
Ahmedabad
Hyderabad
Delhi
Chennai
Chennai
Bangalore
Hyderabad
Lucknow
Mumbai
Ahmedabad
Bhopal
Delhi
Delhi
Bhopal
Delhi
Delhi
Hyderabad
Bhopal
Hyderabad
Bangalore
Mumbai
Hyderabad
Mumbai
Delhi
Mumbai
Hyderabad
Lucknow
Jaipur
Bangalore
Jaipur
Bangalore
Bangalore
Delhi
Surat
Bhopal
Chennai
  Jaipur
Jaipur
Delhi
Delhi
Delhi
Mumbai
Mumbai
Mumbai
Ahmedabad
Nagpur
Delhi
Pune
Delhi
Delhi
  Chennai
Chennai
Hyderabad
Surat
Hyderabad
Chennai
Pune
Mumbai
Mumbai
Hyderabad
Visakhapatnam
Delhi
Mumbai
Lucknow
Bhopal
Mumbai
Surat
Ahmedabad
nan
Nagpur
Hyderabad
Surat
Jaipur
Bangalore
Chennai
Delhi
Jaipur
Delhi
Mumbai
Surat
Bangalore
Mumbai
Delhi
Jaipur
Visakhapatnam
Jaipur
Pune
Delhi
Delhi
Nagpur
Mumbai
Hyderabad
Chennai
Mumbai
Surat
Hyderabad
Ahmedabad
Hyderabad
Pune
Surat
Mumbai
Surat
Mumbai
Bhopal
Delhi
Chennai
Ahmedabad
Delhi
Ahmedabad
Lucknow
Chennai
Ahmedabad
Mumbai
Mumbai
Mumbai
  Delhi
Delhi
nan
Bhopal
Bangalore
Delhi
Nagpur
Visakhapatnam
Mumbai
Nagpur
Delhi
Mumbai
Pune
Mumbai
MUMBAI
Chennai
Bangalore
Mumbai
Bhopal
Bangalore
Chennai
Delhi
Delhi
Hyderabad
Bangalore
Hyderabad
Visakhapatnam
Mumbai
Chennai
Mumbai
Jaipur
Hyderabad
Mumbai
Mumbai
Delhi
Chennai
Pune
Delhi
Pune
Delhi
Mumbai
Mumbai
Jaipur
Hyderabad
Jaipur
Jaipur
Delhi
Chennai
Delhi
Mumbai
Mumbai
Delhi
Mumbai
Nagpur
Delhi
Chennai
Delhi
Delhi
Bangalore
Bangalore
Bhopal
Delhi
Chennai
Chennai
Delhi
Bhopal
Mumbai
Delhi
Delhi
Delhi
Jaipur
Mumbai
Delhi
Mumbai
Mumbai
nan
Delhi
Chennai
Visakhapatnam
Bangalore
Pune
Chennai
Ahmedabad
Delhi
Mumbai
Surat
Bangalore
Mumbai
Mumbai
Delhi
Mumbai
Pune
Delhi
Bangalore
Mumbai
Delhi
Delhi
Mumbai
Mumbai
Surat
Delhi
Chennai
Jaipur
Mumbai
Bangalore
Chennai
Delhi
Delhi
Chennai
Ahmedabad
Delhi
Hyderabad
Chennai
Pune
Mumbai
Hyderabad
Delhi
Bhopal
Surat
Surat
Mumbai
Bangalore
Bangalore
Jaipur
Bangalore
Ahmedabad
Delhi
Mumbai
Mumbai
Mumbai
Surat
Surat
Mumbai
Bhopal
nan
Surat
Hyderabad
Bangalore
Mumbai
Mumbai
Mumbai
Bangalore
Delhi
Mumbai
Delhi
Delhi
Delhi
Kanpur
Bangalore
Delhi
Mumbai
Hyderabad
Chennai
Mumbai
Jaipur
Chennai
Ahmedabad
Bangalore
Jaipur
Hyderabad
Mumbai
Hyderabad
Delhi
Chennai
Mumbai
Ahmedabad
Bangalore
Pune
Mumbai
Hyderabad
MUMBAI
Delhi
Jaipur
Jaipur
Delhi
Mumbai
Delhi
Kanpur
Bangalore
Visakhapatnam
Mumbai
Hyderabad
Bangalore
Lucknow
Delhi
Bangalore
Pune
Delhi
Ahmedabad
Delhi
Bangalore
Jaipur
Ahmedabad
Kanpur
Jaipur
Bangalore
Ahmedabad
Delhi
Delhi
Mumbai
Hyderabad
Bangalore
Ahmedabad
Mumbai
Bangalore
Bangalore
Kanpur
Pune
Delhi
Delhi
Bhopal
Delhi
Mumbai
Delhi
Bangalore
Nagpur
Delhi
Chennai
Hyderabad
Chennai
Delhi
Delhi
Delhi
Jaipur
Surat
Delhi
Bangalore
Mumbai
Delhi
Chennai
Bhopal
Bangalore
Mumbai
Pune
Bangalore
Bangalore
Jaipur
Bangalore
Ahmedabad
Delhi
Delhi
Chennai
Lucknow
Delhi
Chennai
Surat
Ahmedabad
Delhi
Chennai
Chennai
Surat
Pune
nan
Mumbai
Hyderabad
Jaipur
Bhopal
Jaipur
Delhi
Jaipur
Bangalore
Delhi
Mumbai
Chennai
Bangalore
Mumbai
Bangalore
Hyderabad
Delhi
Bangalore
Bangalore
Chennai
Pune
Chennai
Surat
Mumbai
Nagpur
Bangalore
Mumbai
nan
Hyderabad
Delhi
Ahmedabad
Hyderabad
Hyderabad
Pune
Hyderabad
Hyderabad
Mumbai
Nagpur
CHENNAI
Delhi
Jaipur
Chennai
Mumbai
Mumbai
Delhi
Mumbai
Chennai
Mumbai
Ahmedabad
Mumbai
Lucknow
AHMEDABAD
Lucknow
Nagpur
Visakhapatnam
Ahmedabad
Mumbai
Chennai
Mumbai
Delhi
Delhi
Delhi
Hyderabad
Mumbai
Lucknow
Bhopal
Bhopal
Mumbai
Delhi
Surat
Surat
Chennai
Delhi
Hyderabad
Bangalore
Ahmedabad
Bangalore
Chennai
Pune
Chennai
Hyderabad
Mumbai
Mumbai
Mumbai
Chennai
Chennai
Mumbai
Ahmedabad
Delhi
Pune
Bangalore
Chennai
Mumbai
Chennai
Mumbai
Hyderabad
Bangalore
Hyderabad
Delhi
Hyderabad
Delhi
Bangalore
Jaipur
Ahmedabad
Hyderabad
Delhi
Hyderabad
Delhi
Delhi
Hyderabad
Nagpur
Mumbai
Jaipur
Chennai
Chennai
Pune
Bangalore
Hyderabad
Hyderabad
MUMBAI
Mumbai
Delhi
Delhi
Delhi
Hyderabad
Mumbai
Kanpur
Mumbai
Mumbai
Bangalore
Jaipur
Surat
Bangalore
Visakhapatnam
Delhi
Visakhapatnam
Surat
Pune
Bangalore
Bangalore
bhopal
Hyderabad
Mumbai
Jaipur
Delhi
Mumbai
Chennai
Delhi
Bangalore
Delhi
Kanpur
Chennai
Surat
Hyderabad
Mumbai
Surat
Jaipur
Mumbai
Mumbai
Hyderabad
Delhi
Chennai
Mumbai
Delhi
Mumbai
Pune
Jaipur
Mumbai
Chennai
Ahmedabad
Bangalore
Visakhapatnam
Chennai
Jaipur
Chennai
Nagpur
Mumbai
Jaipur
Jaipur
Mumbai
Mumbai
Bangalore
Chennai
Delhi
Bangalore
Bangalore
Bangalore
delhi
Delhi
Hyderabad
Delhi
Mumbai
Mumbai
Hyderabad
Chennai
Pune
Delhi
Bangalore
Delhi
Delhi
Delhi
Delhi
Chennai
Ahmedabad
Surat
Delhi
Chennai
Hyderabad
Ahmedabad
Mumbai
Delhi
Hyderabad
Delhi
Delhi
Jaipur
Delhi
Delhi
Mumbai
Kanpur
Mumbai
Chennai
Lucknow
Ahmedabad
Hyderabad
Hyderabad
Hyderabad
Mumbai
Delhi
Bangalore
Delhi
Bangalore
Mumbai
Bangalore
Visakhapatnam
Delhi
Bhopal
Bangalore
Nagpur
Delhi
Mumbai
HYDERABAD
Visakhapatnam
Hyderabad
Delhi
Mumbai
Jaipur
Hyderabad
Delhi
Ahmedabad
nan
Pune
Jaipur
Jaipur
Hyderabad
Bhopal
Mumbai
Chennai
Mumbai
Bhopal
Bangalore
Pune
Bhopal
hyderabad
Bangalore
Kanpur
Mumbai
Mumbai
Surat
Ahmedabad
Surat
Chennai
Nagpur
Visakhapatnam
Jaipur
Nagpur
Mumbai
Chennai
Chennai
Mumbai
Delhi
Hyderabad
Delhi
Mumbai
Delhi
Chennai
Mumbai
Mumbai
Pune
Delhi
Ahmedabad
Mumbai
Hyderabad
Kanpur
Delhi
Delhi
Delhi
Delhi
Ahmedabad
Hyderabad
Surat
Pune
Bangalore
Bangalore
Bhopal
Jaipur
Hyderabad
Ahmedabad
Pune
Delhi
Jaipur
Jaipur
Mumbai
Delhi
Bangalore
Mumbai
Bangalore
Bangalore
Kanpur
Mumbai
Mumbai
Bangalore
Pune
Jaipur
Nagpur
Pune
Mumbai
Surat
Bhopal
Delhi
Bangalore
Surat
Kanpur
Bangalore
Jaipur
Chennai
Hyderabad
Bhopal
Chennai
Hyderabad
Visakhapatnam
Bangalore
Pune
Bangalore
Bangalore
Bhopal
Pune
Delhi
Bangalore
Delhi
Delhi
Jaipur
Delhi
Delhi
Delhi
Bhopal
chennai
Chennai
Visakhapatnam
Mumbai
Pune
Pune
Nagpur
Chennai
Delhi
Surat
Surat
Mumbai
Nagpur
Ahmedabad

In [44]:
e = []
for j in ty["City"]:
  if j == "KANPUR" or j == "Kanpur" or j == "kanpur":
    e.append(j)
print(e)

['Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'KANPUR', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur', 'Kanpur']

In [47]:
e.index("Kanpur")

0

In [45]:
len(e)

99

In [48]:
ty["City"].sort_values()

1957      Chennai
3323      Chennai
913       Chennai
2022        Delhi
658         Delhi
           ...
4882            NaN
4956            NaN
5059            NaN
5068            NaN
5103            NaN
Name: City, Length: 5171, dtype: object

In [51]:
ty["City"].where((ty["City"] == "KANPUR") | (ty["City"] == "Kanpur"))

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
5166    NaN
5167    NaN
5168    NaN
5169    NaN
5170    NaN
Name: City, Length: 5171, dtype: object

In [54]:
ty['City_cleaned'] = ty['City'].str.strip().str.capitalize()
ty_kanpur = ty[ty['City_cleaned'] == 'Kanpur']
ty_kanpur

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
50,BX_KANPUR_045,BrandX_India Tech Hub Kanpur,BrandX_India,Flagship,Kanpur,Tier2,iPad Pro,Electronics,Tablets,Mature,...,Standard,Low,1.0,276,1,2022,Q1,Spring,Kanpur,Kanpur
119,BX_KANPUR_004,BrandX_India Apparel Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Levi's 511 Jeans,Clothes,Jeans,Discontinued,...,Standard,Medium,7.0,102,1,2022,Q1,Spring,Kanpur,Kanpur
147,BX_KANPUR_019,BrandX_India Superstore Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Tata Tea Premium,Groceries,Tea,New Launch,...,Standard,Low,2.0,51,2,2022,Q1,Spring,Kanpur,Kanpur
211,BX_KANPUR_059,BrandX_India Comfort Kanpur,BrandX_India,Express,Kanpur,Tier2,Samsung 23L Solo,Home Appliances,Microwaves,Growing,...,Standard,Low,2.0,739,2,2022,Q1,Spring,Kanpur,Kanpur
273,BX_KANPUR_069,BrandX_India Accessories Kanpur,BrandX_India,Flagship,Kanpur,Tier2,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Standard,Low,2.0,115,3,2022,Q1,Summer,Kanpur,Kanpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,BX_KANPUR_055,BrandX_India Living Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Bosch 6kg Top Load,Home Appliances,Washing Machines,Discontinued,...,Standard,Low,3.0,455,11,2024,Q4,Winter,Kanpur,Kanpur
5017,BX_KANPUR_055,BrandX_India Electronics Kanpur,BrandX_India,Express,Kanpur,Tier2,iPad Pro,Electronics,Tablets,Growing,...,Standard,Low,7.0,268,12,2024,Q4,Winter,Kanpur,Kanpur
5066,BX_KANPUR_038,BrandX_India Express Kanpur,BrandX_India,Online Hub,Kanpur,Tier2,Tata Tea Premium,Groceries,Tea,Declining,...,Standard,Low,3.0,100,12,2024,Q4,Winter,Kanpur,Kanpur
5163,BX_KANPUR_030,BrandX_India Digital Kanpur,BrandX_India,Mall Store,KANPUR,Tier2,iPhone 14,Electronics,Smartphones,Discontinued,...,Standard,Low,2.0,242,10,2022,Q4,Winter,KANPUR,Kanpur
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur

In [55]:
ty.head(9)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,Competitive,Low,4.0,99,1,2022,Q1,Spring,Mumbai,Mumbai
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,Aggressive,Low,4.0,108,1,2022,Q1,Spring,Delhi,Delhi
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,Competitive,Low,2.0,90,1,2022,Q1,Spring,Mumbai,Mumbai
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,Competitive,Low,3.0,137,1,2022,Q1,Spring,Delhi,Delhi
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,Aggressive,Low,4.0,214,1,2022,Q1,Spring,Mumbai,Mumbai

In [58]:
ty[ty["Store_Type"] == "Flagship"]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
21,BX_MUMBAI_088,BrandX_India Express Mumbai,BrandX_India,Flagship,Mumbai,Metro,Basmati Rice 5kg,Groceries,Rice,Growing,...,Aggressive,Low,6.0,143,1,2022,Q1,Spring,Mumbai,Mumbai
23,BX_PUNE_051,BrandX_India Fashion Pune,BrandX_India,Flagship,Pune,Tier1,Nike Air Max,Clothes,Shoes,Discontinued,...,Competitive,Medium,3.0,121,1,2022,Q1,Spring,Pune,Pune
24,BX_DELHI_061,BrandX_India Home Delhi,BrandX_India,Flagship,Delhi,Metro,IFB 7kg Front Load,Home Appliances,Washing Machines,Declining,...,Aggressive,Low,7.0,665,1,2022,Q1,Spring,Delhi,Delhi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5149,BX_DELHI_054,BrandX_India Style Delhi,BrandX_India,Flagship,Delhi,Metro,Nike Jacket,Clothes,Jackets,Declining,...,Aggressive,Medium,1.0,65,12,2023,Q4,Winter,Delhi,Delhi
5160,BX_MUMBAI_019,BrandX_India Superstore Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Growing,...,Aggressive,Low,1.0,147,10,2024,Q4,Winter,Mumbai,Mumbai
5161,BX_JAIPUR_075,BrandX_India Fashion Jaipur,BrandX_India,Flagship,Jaipur,Tier2,Adidas Hoodie,Clothes,Jackets,Mature,...,Standard,Medium,5.0,98,12,2023,Q4,Winter,Jaipur,Jaipur
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,Competitive,Low,3.0,210,6,2024,Q2,Monsoon,Delhi,Delhi

In [59]:
len(ty[ty["Store_Type"] == "Flagship"])

1055

In [60]:
ty[(ty["Store_Type"] == "Flagship") & (ty["City"] == "Mumbai")]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
21,BX_MUMBAI_088,BrandX_India Express Mumbai,BrandX_India,Flagship,Mumbai,Metro,Basmati Rice 5kg,Groceries,Rice,Growing,...,Aggressive,Low,6.0,143,1,2022,Q1,Spring,Mumbai,Mumbai
26,BX_MUMBAI_019,BrandX_India Mobile Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sony Alpha a7 IV,Gadgets,Cameras,Mature,...,Aggressive,Low,4.0,131,1,2022,Q1,Spring,Mumbai,Mumbai
30,BX_MUMBAI_020,BrandX_India Tech Hub Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sony Bravia 43Inch,Electronics,Smart TVs,Growing,...,Competitive,Low,4.0,209,1,2022,Q1,Spring,Mumbai,Mumbai
37,BX_MUMBAI_092,BrandX_India Accessories Mumbai,BrandX_India,Flagship,Mumbai,Metro,Canon EOS R6,Gadgets,Cameras,New Launch,...,Aggressive,Low,3.0,123,1,2022,Q1,Spring,Mumbai,Mumbai
39,BX_MUMBAI_068,BrandX_India Electronics Mumbai,BrandX_India,Flagship,Mumbai,Metro,Samsung Galaxy S23,Electronics,Smartphones,Declining,...,Competitive,Low,2.0,277,1,2022,Q1,Spring,Mumbai,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5034,BX_MUMBAI_041,BrandX_India Gadget Zone Mumbai,BrandX_India,Flagship,Mumbai,Metro,OnePlus 11,Electronics,Smartphones,Declining,...,Competitive,Low,2.0,219,12,2024,Q4,Winter,Mumbai,Mumbai
5106,BX_MUMBAI_033,BrandX_India Trends Mumbai,BrandX_India,Flagship,Mumbai,Metro,H&M Cotton Tee,Clothes,T-Shirts,Growing,...,Competitive,Medium,6.0,142,12,2024,Q4,Winter,Mumbai,Mumbai
5113,BX_MUMBAI_003,BrandX_India Connect Mumbai,BrandX_India,Flagship,Mumbai,Metro,Mi Power Bank,Gadgets,Power Banks,Discontinued,...,Aggressive,Low,5.0,114,12,2024,Q4,Winter,Mumbai,Mumbai
5126,BX_MUMBAI_086,BrandX_India Fresh Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Mature,...,Aggressive,Low,2.0,145,8,2024,Q3,Monsoon,Mumbai,Mumbai
5133,BX_MUMBAI_066,BrandX_India Appliances Mumbai,BrandX_India,Flagship,Mumbai,Metro,LG Double Door 260L,Home Appliances,Refrigerators,Discontinued,...,Aggressive,Low,5.0,616,7,2022,Q3,Monsoon,Mumbai,Mumbai

In [61]:
ty

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,Standard,Low,6.0,57,1,2022,Q1,Spring,Pune,Pune
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,Competitive,Low,4.0,99,1,2022,Q1,Spring,Mumbai,Mumbai
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,Standard,Medium,3.0,150,11,2024,Q4,Winter,Jaipur,Jaipur
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,Competitive,Low,7.0,136,7,2023,Q3,Monsoon,Mumbai,Mumbai
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,Competitive,Medium,3.0,138,12,2022,Q4,Winter,Mumbai,Mumbai
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,Competitive,Low,3.0,210,6,2024,Q2,Monsoon,Delhi,Delhi

In [63]:
ty[ty.duplicated()]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
5121,BX_BANGALORE_099,BrandX_India Apparel Bangalore,BrandX_India,Mall Store,Bangalore,Metro,H&M Cotton Tee,Clothes,T-Shirts,Declining,...,Aggressive,Medium,7.0,50,8,2023,Q3,Monsoon,Bangalore,Bangalore
5122,BX_MUMBAI_095,BrandX_India Trends Mumbai,BrandX_India,Mall Store,Mumbai,Metro,Adidas Ultraboost,Clothes,Shoes,Discontinued,...,Competitive,Medium,2.0,75,1,2022,Q1,Spring,Mumbai,Mumbai
5123,BX_BANGALORE_058,BrandX_India Digital Bangalore,BrandX_India,Street Store,Bangalore,Metro,iPad Pro,Electronics,Tablets,Mature,...,Aggressive,Low,2.0,257,6,2022,Q2,Monsoon,Bangalore,Bangalore
5124,BX_DELHI_027,BrandX_India Trends Delhi,BrandX_India,Online Hub,Delhi,Metro,Pepe Jeans,Clothes,Jeans,Growing,...,Aggressive,Medium,3.0,86,12,2024,Q4,Winter,Delhi,Delhi
5125,BX_BANGALORE_062,BrandX_India Daily Bangalore,BrandX_India,Street Store,Bangalore,Metro,Tata Tea Premium,Groceries,Tea,Declining,...,Aggressive,Low,5.0,98,4,2024,Q2,Summer,Bangalore,Bangalore
5126,BX_MUMBAI_086,BrandX_India Fresh Mumbai,BrandX_India,Flagship,Mumbai,Metro,Sunflower Oil 1L,Groceries,Oil,Mature,...,Aggressive,Low,2.0,145,8,2024,Q3,Monsoon,Mumbai,Mumbai
5127,BX_BANGALORE_097,BrandX_India Superstore Bangalore,BrandX_India,Mall Store,Bangalore,Metro,Brown Sugar 500g,Groceries,Sugar,Discontinued,...,Aggressive,Low,4.0,115,5,2022,Q2,Summer,Bangalore,Bangalore
5128,BX_CHENNAI_053,BrandX_India Daily Chennai,BrandX_India,Mall Store,Chennai,Metro,White Sugar 1kg,Groceries,Sugar,Discontinued,...,Aggressive,Low,6.0,136,1,2023,Q1,Spring,Chennai,Chennai
5129,BX_BANGALORE_082,BrandX_India Accessories Bangalore,BrandX_India,Online Hub,Bangalore,Metro,JBL Charge 5,Gadgets,Bluetooth Speakers,Discontinued,...,Competitive,Low,5.0,67,5,2023,Q2,Summer,Bangalore,Bangalore
5130,BX_DELHI_079,BrandX_India Smart Delhi,BrandX_India,Flagship,Delhi,Metro,PlayStation 5,Gadgets,Gaming Consoles,Discontinued,...,Aggressive,Low,1.0,53,10,2022,Q4,Winter,Delhi,Delhi
5131,BX_SURAT_090,BrandX_India Apparel Surat,BrandX_India,Express,Surat,Tier2,Levi's T-Shirt,Clothes,T-Shirts,Growing,...,Standard,Medium,7.0,65,7,2024,Q3,Monsoon,Surat,Surat
5132,BX_DELHI_007,BrandX_India Comfort Delhi,BrandX_India,Express,Delhi,Metro,Kent Grand Plus,Home Appliances,Water Purifiers,New Launch,...,Aggressive,High,2.0,715,5,2024,Q2,Summer,Delhi,Delhi
5133,BX_MUMBAI_066,BrandX_India Appliances Mumbai,BrandX_India,Flagship,Mumbai,Metro,LG Double Door 260L,Home Appliances,Refrigerators,Discontinued,...,Aggressive,Low,5.0,616,7,2022,Q3,Monsoon,Mumbai,Mumbai
5134,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
5135,BX_MUMBAI_084,BrandX_India Mobile Mumbai,BrandX_India,Mall Store,Mumbai,Metro,Bose SoundLink,Gadgets,Bluetooth Speakers,Discontinued,...,Competitive,Low,3.0,63,8,2022,Q3,Monsoon,Mumbai,Mumbai
5136,BX_CHENNAI_060,BrandX_India Electronics Chennai,BrandX_India,Online Hub,Chennai,Metro,iPhone 14,Electronics,Smartphones,Discontinued,...,Aggressive,Low,4.0,150,5,2023,Q2,Summer,Chennai,Chennai
5137,BX_SURAT_009,BrandX_India Trends Surat,BrandX_India,Express,Surat,Tier2,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,53,9,2023,Q3,Monsoon,Surat,Surat
5138,BX_DELHI_072,BrandX_India Trends Delhi,BrandX_India,Street Store,Delhi,Metro,H&M Cotton Tee,Clothes,T-Shirts,Mature,...,Competitive,Medium,4.0,105,9,2024,Q3,Monsoon,Delhi,Delhi
5139,BX_NAGPUR_076,BrandX_India Daily Nagpur,BrandX_India,Express,Nagpur,Tier2,Moong Dal 1kg,Groceries,Dal,Discontinued,...,Standard,Low,4.0,129,7,2024,Q3,Monsoon,Nagpur,Nagpur
5140,BX_DELHI_099,BrandX_India Trends Delhi,BrandX_India,Express,Delhi,Metro,Levi's 511 Jeans,Clothes,Jeans,New Launch,...,Competitive,Medium,2.0,69,3,2023,Q1,Summer,Delhi,Delhi
5141,BX_BANGALORE_078,BrandX_India Trends Bangalore,BrandX_India,Online Hub,Bangalore,Metro,Zara Evening Dress,Clothes,Dresses,Declining,...,Competitive,Medium,5.0,148,2,2022,Q1,Spring,Bangalore,Bangalore
5142,BX_MUMBAI_088,BrandX_India Appliances Mumbai,BrandX_India,Express,Mumbai,Metro,Bosch 6kg Top Load,Home Appliances,Washing Machines,New Launch,...,Competitive,Low,3.0,594,12,2023,Q4,Winter,Mumbai,Mumbai
5143,BX_BANGALORE_093,BrandX_India Electronics Bangalore,BrandX_India,Online Hub,Bangalore,Metro,iPad Pro,Electronics,Tablets,Discontinued,...,Competitive,Low,6.0,159,4,2023,Q2,Summer,Bangalore,Bangalore
5144,BX_DELHI_035,BrandX_India Gadget Zone Delhi,BrandX_India,Street Store,Delhi,Metro,Sony Bravia 43Inch,Electronics,Smart TVs,Discontinued,...,Competitive,Low,1.0,141,8,2022,Q3,Monsoon,Delhi,Delhi
5145,BX_BHOPAL_055,BrandX_India Gadget Zone Bhopal,BrandX_India,Street Store,Bhopal,Tier2,OnePlus 11,Electronics,Smartphones,Declining,...,Standard,Low,5.0,209,1,2022,Q1,Spring,Bhopal,Bhopal

In [65]:
ty[ty["City_Tier"].duplicated()]

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season,City_2,City_cleaned
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,Standard,Medium,4.0,101,1,2022,Q1,Spring,Pune,Pune
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,Competitive,Medium,5.0,79,1,2022,Q1,Spring,Chennai,Chennai
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,Competitive,Low,2.0,110,1,2022,Q1,Spring,Chennai,Chennai
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,Aggressive,Low,4.0,108,1,2022,Q1,Spring,Delhi,Delhi
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,Competitive,Low,2.0,90,1,2022,Q1,Spring,Mumbai,Mumbai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,Standard,Medium,3.0,150,11,2024,Q4,Winter,Jaipur,Jaipur
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,Competitive,Low,7.0,136,7,2023,Q3,Monsoon,Mumbai,Mumbai
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,Standard,Low,1.0,222,7,2023,Q3,Monsoon,Kanpur,Kanpur
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,Competitive,Medium,3.0,138,12,2022,Q4,Winter,Mumbai,Mumbai
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,Competitive,Low,3.0,210,6,2024,Q2,Monsoon,Delhi,Delhi